services:
  aestimo-web:
    build: .
    restart: always
    expose:
      - "3000"
    env_file: ./.env
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    env_file: ./.env
    volumes:
      - aestimo_pgdata:/var/lib/postgresql/data

volumes:
  aestimo_pgdata:
