services:
  planpoker_app:
    build: .
    container_name: planpoker-app
    restart: always
    ports:
      - "8080:8080"
    env_file: ./.env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: planpoker-postgres
    restart: always
    env_file: ./.env
    volumes:
      - planpoker_db_data:/var/lib/postgresql/data

volumes:
  planpoker_db_data:
