services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always

  web:
    build: .
    restart: always
    expose:
      - "8080"
    env_file: ./.env
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    env_file: ./.env
    volumes:
      - aestimo_db_data:/var/lib/postgresql/data

volumes:
  aestimo_db_data:

