version: "3.9"

services:
  app:
    build: .
    container_name: ppn-app
    ports:
      - "8080:3000"
    env_file: ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: ppn-postgres
    restart: always
    env_file: ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
